// utl.JSN.getObjectList('records', (Map<String,Object>) JSON.deserializeUntyped(jsonString))
//jsonString = '[null,true,{"Name" : "Test Acc1", "records" : ["hzh","kiwi",{"wt" : "f"},{"aa" : "faa","wata" : {"fa": "ak"}}]}, {"Name":"Test Acc2", "Owner" : {"Name" : "Justus", "Profile" : {"Name" : "System Administrator"}}}]';

//jsonString = '[1,2,3,4,5, [true,false]]';
//(Object[]) JSON.deserializeUntyped(jsonString);